apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob.yaml
configMapGenerator:
- name: jira-wrangler
  files:
  - config.yaml
images:
- name: jira-wrangler
  newName: quay.io/mt-sre/jira-wrangler
  newTag: latest
