---
repos:
# Fixers
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: end-of-file-fixer
  - id: pretty-format-json
    args:
      - --autofix
  - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt

- repo: local
  hooks:
  - id: go-mod-tidy
    name: go-mod-tidy
    language: system
    entry: ./mage check:tidy
    pass_filenames: false
    always_run: true
    require_serial: true
  - id: go-mod-verify
    name: go-mod-verify
    language: system
    entry: ./mage check:verify
    pass_filenames: false
    always_run: true
    require_serial: true

# Checkers
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key

- repo: local
  hooks:
  - id: golangci-lint
    name: golangci-lint
    language: system
    entry: ./mage check:lint
    pass_filenames: false
    types: [go]
    require_serial: true
